# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://jinlang226.github.io"
# Language used
languageCode = "en-us"
# Website title
title = "Home"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "Posts"
    url = "/post"
    weight = -140

#[[menu.main]]
#	name = "Research"
#	url = "/research"
#	weight = -150

#[[menu.main]]
#	name = "Projects"
#	url = "/projects"
#	weight = -140

# Make the tags and categories pages accessible directly from the navbar.
#[[menu.main]]
#    name = "Teaching"
#    url = "/teaching"
#    weight = -130

#[[menu.main]]
#    name = "Service"
#    url = "/service"
#    weight = -120

#[[menu.main]]
#	name = "Tags"
#	url = "/tags"
#	weight = -110

#[[menu.main]]
#    name = "Categories"
#    url = "/categories/"
#    weight = -100

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """Jinlang Wang's homepage"""
    # Author of the site
    authorName = "Jinlang Wang"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/main.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"
